medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: EYObed@123
      port: 5432
      dbname: medical_warehouse
      schema: analytics
      threads: 4
      keepalives_idle: 0
