version: 2

models:

  - name: dim_channels
    description: >
      Dimension table containing one row per Telegram channel.
      Stores channel metadata and aggregated engagement metrics.
    columns:
      - name: channel_key
        description: Surrogate primary key for the channel dimension.
        tests:
          - not_null
          - unique

      - name: channel_name
        description: Telegram channel username (without @).
        tests:
          - not_null

      - name: channel_type
        description: Business classification of the channel (Pharmaceutical, Cosmetics, Medical).
        tests:
          - not_null

      - name: first_post_date
        description: Date of the earliest message observed in the channel.

      - name: last_post_date
        description: Date of the most recent message observed in the channel.

      - name: total_posts
        description: Total number of messages scraped for the channel.

      - name: avg_views
        description: Average number of views per message for the channel.

  - name: dim_dates
    description: >
      Date dimension table used for time-based analysis.
      Enables filtering and grouping by calendar attributes.
    columns:
      - name: date_key
        description: Surrogate key in YYYYMMDD format.
        tests:
          - not_null
          - unique

      - name: full_date
        description: Full calendar date.
        tests:
          - not_null

      - name: day_of_week
        description: ISO day of week number (1=Monday, 7=Sunday).

      - name: day_name
        description: Name of the day (Monday, Tuesday, etc.).

      - name: week_of_year
        description: ISO week number.

      - name: month
        description: Month number (1–12).

      - name: month_name
        description: Name of the month.

      - name: quarter
        description: Calendar quarter (1–4).

      - name: year
        description: Calendar year.

      - name: is_weekend
        description: Indicates whether the date falls on a weekend.

  - name: fct_messages
    description: >
      Fact table containing one row per Telegram message.
      Stores message content and engagement metrics.
    columns:
      - name: message_id
        description: Telegram message ID (natural key).
        tests:
          - not_null
          - unique

      - name: channel_key
        description: Foreign key to dim_channels.
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key

      - name: date_key
        description: Foreign key to dim_dates.
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key

      - name: message_text
        description: Text content of the Telegram message.
        tests:
          - not_null

      - name: message_length
        description: Length of the message text in characters.

      - name: view_count
        description: Number of times the message was viewed.

      - name: forward_count
        description: Number of times the message was forwarded.

      - name: has_image
        description: Boolean flag indicating whether the message contains an image.
